name: LearnAndShareLive CI checks
on: [pull_request]
jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        id: hello-world
        run: sudo /bin/bash ./.github/actions/run.sh
